# Change these first
owner: azuma-healthtech-public # Your GitHub organization or username, where this repository lives
repo: uptime-qss # The name of this repository

sites:
  - name: "azuma: API"
    url: https://qss.azuma-health.tech/health/doa-gateway
  - name: "azuma: Zero Trust Gateway"
    url: https://qss.azuma-health.tech/health/gateway
  - name: "azuma: Mimoto"
    url: https://qss.azuma-health.tech/health/mimoto-auth
  - name: "azuma doa: Identity Service"
    url: https://qss.azuma-health.tech/health/doa-idp
  - name: "azuma doa: Permissions & Access Control"
    url: https://qss.azuma-health.tech/health/doa-acl
  - name: "azuma doa: OAuth 2.0 and OpenID Connect Provider"
    url: https://qss.azuma-health.tech/health/doa-oidc
  - name: "azuma doa: Tenant & Organization Service"
    url: https://qss.azuma-health.tech/health/doa-organization
  - name: "azuma doa: Administration Service"
    url: https://qss.azuma-health.tech/health/doa-admin
  - name: "azuma doa: Mailing Service"
    url: https://qss.azuma-health.tech/health/doa-mailing

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.qss.azuma-health.tech
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/azuma-healthtech-public/uptime-qss/master/assets/logo-1.svg
  name: azuma Status (QSS)
  introTitle: "**azuma** Status (QSS)"
  introMessage: This is an overview page, which uses **real-time** data to display live service status, maintenance windows as well as active and past incidents.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO



workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "0 */8 * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
